name: skagit-met
channels:
  - conda-forge
dependencies:
  - python=3.10.*
  - herbie-data
  - ipykernel
  - cartopy
  - wgrib2
  - geojson
  - zarr
  - pygrib
  - cfgrib
  - dask
  - flox
  - xarray
  - boto3
  - netCDF4
  - metpy
  - xcdat
  - ipympl
  - contextily
  - rioxarray
  - pip
  - rioxarray
  - virtualizarr
  - xoak
  - numba
  - elevation
  - pip:
      - metloom
      - folium
      - mapclassify
      - pyPRISMClimate
      - SynopticPy
prefix: ./env
