[project]
authors = ["Jesse Akes <akesjesse@gmail.com>"]
channels = ["conda-forge"]
description = "Analysis of Meterological data in the Skagit River Basin"
name = "skagit-met"
platforms = ["osx-arm64", "linux-64", "osx-64"]
version = "0.1.0"

[feature.data-download.tasks]
hrr = "python scripts/hrrr_downloader.py"
wrf = "python scripts/wrf_downloader.py"
prism = "python scripts/prism_downloader.py"
ornl = "python scripts/ornl_downloader.py"
snotel = "python scripts/snotel_downloader.py"

[feature.analysis.tasks]
nb = "jupyter lab"

[environments]
data-download = {features = ["data-download"], no-default-feature = true}
analysis = ["analysis"]

[feature.data-download.dependencies]
python = "3.10.*"
herbie-data = "*"
wgrib2 = "*"
geojson = "*"
zarr = "*"
pygrib = "*"
cfgrib = "*"
dask = "*"
flox = "*"
xarray = "*"
boto3 = "*"
netcdf4 = "*"
geopandas = ">=0.9.0,<1.0.0"
numpy = "*"
rioxarray = "*"
fsspec = "*"

[feature.data-download.pypi-dependencies]
pyprismclimate = "*"
metloom = "*"

[feature.analysis.dependencies]
python = "3.11.*"
ipykernel = "*"
cartopy = "*"
zarr = "*"
dask = "*"
flox = "*"
xarray = "*"
netcdf4 = "*"
xcdat = "*"
ipympl = "*"
contextily = "*"
pip = "*"
jupyterlab = "*"
pixi-kernel = "*"
rioxarray = "*"
virtualizarr = "*"
xoak = "*"
synopticpy = "*"
elevation = "*"
regionmask = "*"
geopandas = "*"
kerchunk = "*"
fastparquet = "*"
holoviews = "*"
hvplot = "*"

[pypi-dependencies]
